name = "glam"
version = "1.0.0"
description = "A package to help you easily pretty print structured data"

licences = ["Apache-2.0"]
repository = { type = "github", user = "giacomocavalieri", repo = "glam" }
internal_modules = ["examples", "examples/*"]

[dependencies]
gleam_stdlib = "~> 0.30"

[dev-dependencies]
gleeunit = "~> 0.10"

[documentation]
pages = [
  { title = "A step by step introduction", path = "01_gleam_lists.html", source = "./tutorials/01_gleam_lists.md" },
]
